image: docker:stable

services:
  - docker:dind

variables:
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest --tag $IMAGE_NAME:$CI_BUILD_REF --tag $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_BUILD_REF
    - docker push $IMAGE_NAME:latest